version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  db: # 서비스 명
    image: mysql:8 # 사용할 이미지
    container_name: my-mysql # 컨테이너 이름 설정
    ports:
      - 3306:3306 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: password
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/dev/mysql:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)`
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: my-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  #    volumes:
  #      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #    networks:
  #      - rabbitmq_go_net
  redis:
    image: redis:5.0.3-alpine
    container_name: my-redis
    ports:
      - 6379:6379

networks:
  rabbitmq_go_net:
    driver: bridge